cc_library (
    name = "duration_process",
    hdrs = ["duration_process.h"],
    srcs = ["duration_process.cc"],
    visibility = ["//visibility:public"],
    deps = [
        "//mediapipe/framework/port:logging",
        "//mediapipe/framework:timestamp",
    ]
)