input_stream: "input_video"
output_stream: "output_video"

node: {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: 'FINISHED'
    back_edge: true
  }
  input_side_packet: "MAX_IN_FLIGHT:max_in_flight"
  output_stream: "throttled_input_video"
  node_options: {
    [type.googleapis.com/mediapipe.FlowLimiterCalculatorOptions] {
      max_in_flight: 1
      max_in_queue: 0
    }
  }
}

node: {
  calculator: "StartLatencyCalculator"
  input_stream: "IMAGE_GPU:throttled_input_video"
  output_stream: "IMAGE_GPU:input_video_ltc"
  output_stream: "START_TIME:start_time"
}

# Object detection
node: {
  calculator: "ObjectDetectionEfficientDetSubgraph"
  input_stream: "IMAGE_GPU:input_video_ltc"
  output_stream: "DETECTIONS:detections"
}
# node: {
#   calculator: "ObjectDetectionMobilenetV2Subgraph"
#   input_stream: "IMAGE_GPU:input_video_ltc"
#   output_stream: "DETECTIONS:detections"
# }
node: {
  calculator: "ObjectDetectionRenderSubgraph"
  input_stream: "DETECTIONS:detections"
  input_stream: "IMAGE_GPU:input_video_ltc"
  output_stream: "IMAGE_GPU:output_image_0"
}

# Detects faces and corresponding landmarks.
node: {
  calculator: "ConstantSidePacketCalculator"
  output_side_packet: "PACKET:num_faces"
  node_options: {
    [type.googleapis.com/mediapipe.ConstantSidePacketCalculatorOptions]: {
      packet: { int_value: 1 }
    }
  }
}
node: {
  calculator: "FaceLandmarkFrontGpu"
  input_stream: "IMAGE:input_video_ltc"
  input_side_packet: "NUM_FACES:num_faces"
  output_stream: "LANDMARKS:multi_face_landmarks"
  output_stream: "ROIS_FROM_LANDMARKS:face_rects_from_landmarks"
  output_stream: "DETECTIONS:face_detections_iris"
  output_stream: "ROIS_FROM_DETECTIONS:face_rects_from_detections"
}
# Yawn
node: {
  calculator: "YawnCalculator"
  input_stream: "MULTI_LANDMARKS:multi_face_landmarks"
  output_stream: "YAWN:yawn"
  node_options: {
    [type.googleapis.com/mediapipe.YawnCalculatorOptions]: {
      mar_threshold: 0.85
      verbose: false
      duration_s_threshold: 0.85
    }
  }
}
# Iris
# Gets the very first and only face from "multi_face_landmarks" vector.
node: {
  calculator: "SplitNormalizedLandmarkListVectorCalculator"
  input_stream: "multi_face_landmarks"
  output_stream: "face_landmarks"
  node_options: {
    [type.googleapis.com/mediapipe.SplitVectorCalculatorOptions] {
      ranges: { begin: 0 end: 1 }
      element_only: true
    }
  }
}
node: {
  calculator: "IrisLandmarksSubgraph"
  input_stream: "FACE_LANDMARKS:face_landmarks"
  input_stream: "IMAGE_GPU:input_video_ltc"
  output_stream: "LEFT_EYE_CONTOUR_LANDMARKS:left_eye_contour_landmarks"
  output_stream: "LEFT_EYE_IRIS_LANDMARKS:left_iris_landmarks"
  output_stream: "LEFT_EYE_ROI:left_eye_rect_from_landmarks"
  output_stream: "RIGHT_EYE_CONTOUR_LANDMARKS:right_eye_contour_landmarks"
  output_stream: "RIGHT_EYE_IRIS_LANDMARKS:right_iris_landmarks"
  output_stream: "RIGHT_EYE_ROI:right_eye_rect_from_landmarks"
}
# render iris and face landmarks
node: {
  calculator: "IrisAndFaceLandmarkRenderSubgraph"
  input_stream: "IMAGE_GPU:output_image_0"
  input_stream: "ROIS_FROM_LANDMARKS:face_rects_from_landmarks" #
  input_stream: "MULTI_FACE_LANDMARKS:multi_face_landmarks" #
  input_stream: "EYE_LANDMARKS_LEFT:left_eye_contour_landmarks" #
  input_stream: "EYE_LANDMARKS_RIGHT:right_eye_contour_landmarks" #
  input_stream: "IRIS_LANDMARKS_LEFT:left_iris_landmarks" #
  input_stream: "IRIS_LANDMARKS_RIGHT:right_iris_landmarks" #
  input_stream: "LEFT_EYE_RECT:left_eye_rect_from_landmarks" #
  input_stream: "RIGHT_EYE_RECT:right_eye_rect_from_landmarks" #
  input_stream: "FACE_DETECTIONS:face_detections_iris"
  output_stream: "IMAGE_GPU:output_image_1"
}


node: {
  calculator: "AllEyesClosedCalculator"
  input_stream: "LEFT_EYE_CONTOUR_LANDMARKS:left_eye_contour_landmarks"
  input_stream: "RIGHT_EYE_CONTOUR_LANDMARKS:right_eye_contour_landmarks"
  output_stream: "ALL_EYES_CLOSED:all_eyes_closed"
  node_options: {
    [type.googleapis.com/mediapipe.AllEyesClosedCalculatorOptions]: {
      ear_threshold: 0.3
      duration_s_threshold: 0.75
      verbose: false
    }
  }
}
# Gaze calculator
node: {
  calculator: "GazeCalculator"
  input_stream: "LEFT_IRIS_LANDMARKS:left_iris_landmarks"
  input_stream: "RIGHT_IRIS_LANDMARKS:right_iris_landmarks"
  input_stream: "IMAGE_GPU:input_video_ltc"
  input_stream: "FACE_LANDMARKS:face_landmarks"
  output_stream: "GAZE_RENDER_DATA:gaze_render_data"
  output_stream: "LEFT_GAZE_DIRECTION:left_gaze_direction"
  output_stream: "RIGHT_GAZE_DIRECTION:right_gaze_direction"
  node_options: {
    [type.googleapis.com/mediapipe.GazeCalculatorOptions]: {
      verbose: false
      color: { r: 0 g: 255 b: 0 }
      thickness: 4.0
    }
  }
}

# Hand tracking
node: {
  calculator: "ConstantSidePacketCalculator"
  output_side_packet: "PACKET:num_hands"
  node_options: {
    [type.googleapis.com/mediapipe.ConstantSidePacketCalculatorOptions]: {
      packet: { 
        int_value: 4
      }
    }
  }
}
node: {
  calculator: "HandLandmarkTrackingGpu"
  input_stream: "IMAGE:input_video_ltc"
  input_side_packet: "NUM_HANDS:num_hands"
  output_stream: "LANDMARKS:hand_landmarks"
  output_stream: "HANDEDNESS:handedness"
  output_stream: "PALM_DETECTIONS:palm_detections"
  output_stream: "HAND_ROIS_FROM_LANDMARKS:hand_rects_from_landmarks"
  output_stream: "HAND_ROIS_FROM_PALM_DETECTIONS:hand_rects_from_palm_detections"
}
node: {
  calculator: "HandLandmarksRenderSubgraph"
  input_stream: "IMAGE:output_image_1"
  input_stream: "LANDMARKS:hand_landmarks"
  output_stream: "IMAGE:output_image_2"
}

node: {
  calculator: "SOSHandSignCalculator"
  input_stream: "LANDMARKS:hand_landmarks"
  output_stream: "SOS:sos"
  node_options: {
    [type.googleapis.com/mediapipe.SOSHandSignCalculatorOptions]: {
      max_transform_duration_s_threshold: 0.5
      min_keep_duration_s_threshold: 0.3
      verbose: true
    }
  }
}
# Hand hold distracting object
node: {
  calculator: "HandHoldObjectCalculator"
  input_stream: "LANDMARKS:hand_landmarks"
  input_stream: "DETECTIONS:detections"
  output_stream: "HOLD:hand_hold_cell_phone"
  node_options: {
    [type.googleapis.com/mediapipe.HandHoldObjectCalculatorOptions]: {
      duration_s_threshold: 1
      label: "smartphone"
      verbose: false
    }
  }
}
node: {
  calculator: "HandHoldObjectCalculator"
  input_stream: "LANDMARKS:hand_landmarks"
  input_stream: "DETECTIONS:detections"
  output_stream: "HOLD:hand_hold_cup"
  node_options: {
    [type.googleapis.com/mediapipe.HandHoldObjectCalculatorOptions]: {
      duration_s_threshold: 1
      label: "cup"
      verbose: false
    }
  }
}
node: {
  calculator: "HandHoldObjectCalculator"
  input_stream: "LANDMARKS:hand_landmarks"
  input_stream: "DETECTIONS:detections"
  output_stream: "HOLD:hand_hold_drink"
  node_options: {
    [type.googleapis.com/mediapipe.HandHoldObjectCalculatorOptions]: {
      duration_s_threshold: 0.5
      label: "drink"
      verbose: false
    }
  }
}
# Threaten detection
node: {
  calculator: "FaceDetectionShortRangeGpu"
  input_stream: "IMAGE:input_video_ltc"
  output_stream: "DETECTIONS:face_detections"
}
node: {
  calculator: "ThreatenCalculator"
  input_stream: "MULTI_HAND_LANDMARKS:hand_landmarks"
  input_stream: "OBJECT_DETECTIONS:detections"
  input_stream: "FACE_DETECTIONS:face_detections"
  output_stream: "THREATEN:threaten"
  output_stream: "FACE_MARGIN_DETECTIONS:face_margin_detections"
  node_options: {
    [type.googleapis.com/mediapipe.ThreatenCalculatorOptions]: {
      labels: "scissors"
      labels: "knife"
      labels: "gun"
      verbose: true
      face_margin_top_ratio: 1
      face_margin_left_ratio: 0.5
      face_margin_right_ratio: 0.5
      face_margin_bottom_ratio: 0.5
    }
  }
}
node: {
  calculator: "DetectionsToRenderDataCalculator"
  input_stream: "DETECTIONS:face_margin_detections"
  output_stream: "RENDER_DATA:face_margin_detections_render_data"
  node_options: {
    [type.googleapis.com/mediapipe.DetectionsToRenderDataCalculatorOptions] {
      thickness: 4.0
      color: { r: 0 g: 0 b: 255 }
    }
  }
}
node: {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "IMAGE_GPU:output_image_2"
  input_stream: "face_margin_detections_render_data"
  input_stream: "gaze_render_data"
  output_stream: "IMAGE_GPU:output_image_3"
}
# Audio alert
node: {
  calculator: "AudioAlertCalculator"
  input_stream: "TRIGGER:yawn"
  node_options: {
    [type.googleapis.com/mediapipe.AudioAlertCalculatorOptions]: {
      audio_path: "/home/nextwave/Desktop/T-DMS/T-DMS_mediapipe/alert_audio/yawn_detected.wav"
      play_duration_s: -1
      cool_duration_s: 2
    }
  }
}
node: {
  calculator: "AudioAlertCalculator"
  input_stream: "TRIGGER:all_eyes_closed"
  node_options: {
    [type.googleapis.com/mediapipe.AudioAlertCalculatorOptions]: {
      audio_path: "/home/nextwave/Desktop/T-DMS/T-DMS_mediapipe/alert_audio/drowsiness_detected.wav"
      play_duration_s: -1
      cool_duration_s: 2
    }
  }
}
node: {
  calculator: "AudioAlertCalculator"
  input_stream: "TRIGGER:sos"
  node_options: {
    [type.googleapis.com/mediapipe.AudioAlertCalculatorOptions]: {
      audio_path: "/home/nextwave/Desktop/T-DMS/T-DMS_mediapipe/alert_audio/SOS_detected.wav"
      play_duration_s: -1
      cool_duration_s: 2
    }
  }
}
node: {
  calculator: "AudioAlertCalculator"
  input_stream: "TRIGGER:hand_hold_cell_phone"
  node_options: {
    [type.googleapis.com/mediapipe.AudioAlertCalculatorOptions]: {
      audio_path: "/home/nextwave/Desktop/T-DMS/T-DMS_mediapipe/alert_audio/using_smartphone_detected.wav"
      play_duration_s: -1
      cool_duration_s: 2
    }
  }
}
node: {
  calculator: "AudioAlertCalculator"
  input_stream: "TRIGGER:hand_hold_cup"
  node_options: {
    [type.googleapis.com/mediapipe.AudioAlertCalculatorOptions]: {
      audio_path: "/home/nextwave/Desktop/T-DMS/T-DMS_mediapipe/alert_audio/holding_drink_detected.wav"
      play_duration_s: -1
      cool_duration_s: 2
    }
  }
}
node: {
  calculator: "AudioAlertCalculator"
  input_stream: "TRIGGER:hand_hold_drink"
  node_options: {
    [type.googleapis.com/mediapipe.AudioAlertCalculatorOptions]: {
      audio_path: "/home/nextwave/Desktop/T-DMS/T-DMS_mediapipe/alert_audio/holding_drink_detected.wav"
      play_duration_s: -1
      cool_duration_s: 2
    }
  }
}
# node: {
#   calculator: "AudioAlertCalculator"
#   input_stream: "TRIGGER:threaten"
#   node_options: {
#     [type.googleapis.com/mediapipe.AudioAlertCalculatorOptions]: {
#       audio_path: "/home/nextwave/Desktop/T-DMS/T-DMS_mediapipe/alert_audio/alert.wav"
#       play_duration_s: 3
#       cool_duration_s: 1
#     }
#   }
# }
# === Server interaction
  # === Cooling
node: {
  calculator: "CoolingCalculator"
  input_stream: "TRIGGER:sos"
  output_stream: "TRIGGER:sos_cooling"
  node_options: {
    [type.googleapis.com/mediapipe.CoolingCalculatorOptions]: {
      cool_duration_s: 30
      verbose: false
    }
  }
}
node: {
  calculator: "CoolingCalculator"
  input_stream: "TRIGGER:threaten"
  output_stream: "TRIGGER:threaten_cooling"
  node_options: {
    [type.googleapis.com/mediapipe.CoolingCalculatorOptions]: {
      cool_duration_s: 30
      verbose: false
    }
  }
}
  # === Http Post
node: {
  calculator: "HttpPostCalculator"
  input_stream: "TRIGGER:sos_cooling"
  output_stream: "RESPONSE:sos_http_post_response"
  node_options: {
    [type.googleapis.com/mediapipe.HttpPostCalculatorOptions]: {
      url: "https://scity-dev.innovation.com.vn/api/device/alarm/noauth/AICAM003"
      payload_path: "http_post_payload/sos_alert.json"
      verbose: true
    }
  }
}
node: {
  calculator: "HttpPostCalculator"
  input_stream: "TRIGGER:threaten_cooling"
  output_stream: "RESPONSE:threaten_http_post_response"
  node_options: {
    [type.googleapis.com/mediapipe.HttpPostCalculatorOptions]: {
      url: "https://scity-dev.innovation.com.vn/api/device/alarm/noauth/AICAM002"
      payload_path: "http_post_payload/threaten_alert.json"
      verbose: true
    }
  }
}
  # === Send image
node: {
  calculator: "ConditionCalculator"
  input_stream: "sos_cooling"
  input_stream: "threaten_cooling"
  output_stream: "post_image_signal"
  node_options: {
    [type.googleapis.com/mediapipe.ConditionCalculatorOptions]: {
      logic_type: OR
    }
  }
}
node: {
  calculator: "GateCalculator"
  input_stream: "ALLOW:post_image_signal"
  input_stream: "output_image_3"
  output_stream: "output_image_3_cond_ck"
}
node: {
  calculator: "GpuBufferToImageFrameCalculator"
  input_stream: "output_image_3_cond_ck"
  output_stream: "output_image_3_cpu"
}

# node: {
#   calculator: "ConditionCalculator"
#   input_stream: "CONDITION:0:sos_cooling"
#   input_stream: "CONDITION:1:threaten_cooling"
#   input_stream: "output_image_3_cpu"
#   output_stream: "RESULT:cond_res"
#   output_stream: "output_image_3_cond_ck"
#   node_options: {
#     [type.googleapis.com/mediapipe.ConditionCalculatorOptions]: {
#       logic_type: OR
#     }
#   }
# }
node: {
  calculator: "ImageFrameToBase64StringCalculator"
  input_stream: "output_image_3_cpu"
  output_stream: "output_image_3_base64"
}
node: {
  calculator: "MqttCalculator"
  input_stream: "PAYLOAD_IMAGE:output_image_3_base64"
  node_options: {
    [type.googleapis.com/mediapipe.MqttCalculatorOptions] {
      broker_address: "scity-dev.innovation.com.vn"
      port: 1883
      client_id: "aicamera"
      username: "halow"
      password: "halow"
      telemetry_topic: "v1/devices/6587617b-9054-45da-b1f4-f4a8d460acd4/telemetry"
      attribute_topic: "v1/devices/6587617b-9054-45da-b1f4-f4a8d460acd4/attribute"
      verbose: true
    }
  }
}
node: {
  calculator: "LatencyCalculator"
  input_stream: "START_TIME:start_time"
  input_stream: "IMAGE_GPU:output_image_3"
  input_stream: "THREATEN:threaten"
  input_stream: "SOS:sos"
  input_stream: "ALL_EYES_CLOSED:all_eyes_closed"
  input_stream: "HAND_HOLD_CELL_PHONE:hand_hold_cell_phone"
  input_stream: "HAND_HOLD_DRINK:hand_hold_drink"
  output_stream: "IMAGE_GPU:output_image_4"
  output_stream: "THREATEN:threaten_1"
  output_stream: "SOS:sos_1"
  output_stream: "ALL_EYES_CLOSED:all_eyes_closed_1"
  output_stream: "HAND_HOLD_CELL_PHONE:hand_hold_cell_phone_1"
  output_stream: "HAND_HOLD_DRINK:hand_hold_drink_1"
  output_stream: "FPS:fps"
  output_stream: "LATENCY:latency"

  node_options: {
    [type.googleapis.com/mediapipe.LatencyCalculatorOptions] {
      label: "Main flow"
      verbose: false
    }
  }
}
node: {
  calculator: "TextRenderDataCalculator"
  input_stream: "FPS:fps"
  input_stream: "THREATEN:threaten"
  input_stream: "SOS:sos"
  input_stream: "ALL_EYES_CLOSED:all_eyes_closed"
  input_stream: "YAWN:yawn"
  input_stream: "HAND_HOLD_CELL_PHONE:hand_hold_cell_phone"
  input_stream: "HAND_HOLD_DRINK:hand_hold_drink"
  output_stream: "TEXT_RENDER_DATA:text_render_data"
  node_options: {
    [type.googleapis.com/mediapipe.TextRenderDataCalculatorOptions] {
      warning_color: { r: 255 g: 0 b: 0 }
      normal_color: { r: 0 g: 0 b: 255 }
      content_color: { r: 255 g: 255 b: 255 }
      font_height: 0.02
      normalized: true
      font_face: 1
      line_gap: 0.04
      left: 0.01
      init_baseline: 0.04
      outline_thickness: 0.5
    }
  }
}
node: {
  calculator: "AnnotationOverlayCalculator"
  input_stream: "IMAGE_GPU:output_image_4"
  input_stream: "text_render_data"
  output_stream: "IMAGE_GPU:output_video"
}
